#!/usr/bin/env ruby

Dir[File.dirname(__FILE__) + '/lib/*.rb'].each {|file| require file }

case ARGV[0]
when 'install', 'in'
  Zypper.install ARGV[1]
when 'list'
  Zypper.list
when 'remove', 'rm'
  Zypper.remove ARGV[1]
when 'search', 'se'
  Zypper.search ARGV[1]
else
  puts 'wrooong!'
end

